---

language: go

go:
  - 1.7.5
  - 1.8

install:
  - go get github.com/Masterminds/glide
  - pip install cram --user

before_script:
  - go vet -v `glide nv`

script:
  - GOOS=linux GOARCH=amd64 go build -o certigo-linux-amd64
  - GOOS=darwin GOARCH=amd64 go build -o certigo-darwin-amd64
  - GOOS=windows GOARCH=amd64 go build -o certigo-windows-amd64.exe
  - go test -v `glide nv`
  - ln -s certigo-linux-amd64 certigo
  - PATH=$PWD:$PATH cram -v tests/*.t

deploy:
  provider: releases
  api_key:
    secure: i+82k3Khvke2ejCJ3B+BE0nsemPSXnwcm4cDtuC8BF3vXPSO36hIbPDZ+mnGlqiGw54tduY3jrytCwo1YHnxu8veT3cJ27p9wDQt7Lz6kLf1wRHBp180PL2bfz1tOugtDsAw9D78EJj0LvWtupY0CmzXl8idVua1T9Z5HTR4V28QoDw0JY/+GB+Aq+C51oyDcICtLJBVhc4Wl/K7AqZPWEBC/kn1fG6BYbFIHCNLho4qiCLW9aQdFL5usHJ07992VBlzXLSkP9WU1w/pZ1kT4YaopusyQH8FG1be+V8hf74N0I9vhR/YRTK4cOuAo3Gu87HiEK0U9pgubyoYTRWeZYS9ryVH8Wa7QelauWbH16OWeWv18w98/8aaKE7RgZHlrMFwXnzzFokXuFqzMNWKOP5QxMOqlkY6UcgwS7RqbjxvHyzfapb212s5qgN1LAE85fys2ExMFEPO2NLry9PZVD2bHbQ+Y6bQg6XiI8Kvvmz0dRaY+chADpDNjIK+zpDwc3o1MjvnwiUt7AZrj4PvVD381E0X3JWmMeOOaW46LC5hn5Bhobl6wDC1crgf3QAqfMhFlAd+O0j7qOrW31vm1wPMtaeNQIAq/xjGROvLeBgKlzx1bfK51YQxIC3wRA2AVrxispHkq+rK30lGPhNHWLb91qy4tuy7y1sUAnwm8Dk=
  file:
   - certigo-linux-amd64
   - certigo-darwin-amd64
   - certigo-windows-amd64.exe
  skip_cleanup: true
  on:
    repo: square/certigo
    tags: true
    go: 1.8
